const Section = ({ title, children }) => (
    <div className="policy-section">
        <h2 className="policy-heading">{title}</h2>
        {children}
    </div>
);

export default function TermsPage() {
    return (
        <div className="info-page fade-in">
            <section className="info-hero">
                <span className="info-tag">◎ Legal</span>
                <h1 className="info-hero-title">
                    Terms &amp; <span className="text-accent">Conditions</span>
                </h1>
                <p className="info-hero-sub">
                    Last updated: March 2026 · Subconscious Influence Mapper (SIM)
                </p>
            </section>

            <section className="info-section">
                <div className="policy-doc">
                    <Section title="1. Acceptance of Terms">
                        <p>
                            By accessing and using the Subconscious Influence Mapper platform ("SIM",
                            "the Platform"), you accept and agree to be bound by these Terms and Conditions.
                            If you do not agree to these terms, please do not use the Platform.
                        </p>
                    </Section>

                    <Section title="2. Platform Purpose">
                        <p>
                            SIM is an experimental research and educational tool designed to help users
                            understand cognitive biases through interactive behavioral experiments.
                            The platform is provided for educational and research purposes only. It is
                            <strong> not</strong> a clinical diagnostic tool, medical device, or psychological
                            assessment instrument recognized by any regulatory body.
                        </p>
                    </Section>

                    <Section title="3. Responsible Use Guidelines">
                        <ul className="policy-list">
                            <li>You must be at least 16 years of age to use this platform.</li>
                            <li>You agree to participate in experiments honestly and without attempting to manipulate or game the scoring algorithm.</li>
                            <li>You may not use automated tools, bots, or scripts to interact with the experiment interface.</li>
                            <li>You may not attempt to reverse-engineer, scrape, or extract the experimental question bank or scoring algorithm.</li>
                            <li>You may not share your account credentials with others. Each account must represent one individual.</li>
                            <li>You agree not to use the platform in a way that could harm, impair, or overload our infrastructure.</li>
                        </ul>
                    </Section>

                    <Section title="4. Experiment Data & Results Disclaimer">
                        <p>
                            The bias scores and Manipulation Vulnerability Index (MVI) generated by SIM
                            are approximations based on behavioral signals recorded during web-based
                            experiments. These scores are intended as educational indicators only.
                        </p>
                        <p style={{ marginTop: 12 }}>
                            SIM makes no warranties regarding the accuracy, completeness, or scientific
                            validity of individual results. Do not make clinical, legal, employment, or
                            major personal decisions based solely on your SIM results.
                        </p>
                    </Section>

                    <Section title="5. Intellectual Property">
                        <p>
                            All content on the SIM platform — including the experimental question bank,
                            scoring algorithms, design system, and analytical methodology — is the
                            intellectual property of the SIM development team. You may not reproduce,
                            distribute, or create derivative works from this content without written permission.
                        </p>
                        <p style={{ marginTop: 12 }}>
                            Your personal experiment data and analytics belong to you. You retain full
                            ownership of your own results and may export them at any time.
                        </p>
                    </Section>

                    <Section title="6. Data Usage">
                        <p>
                            By using the platform, you consent to the collection and use of your behavioral
                            telemetry data as described in our{" "}
                            <a href="/privacy" className="auth-link">Privacy Policy</a>.
                            Aggregate, anonymized data may be used for platform improvement and research
                            publications. Personally identifiable data is never shared with third parties.
                        </p>
                    </Section>

                    <Section title="7. Platform Availability & Limitations">
                        <ul className="policy-list">
                            <li>SIM is provided "as is" without warranties of any kind, express or implied.</li>
                            <li>We do not guarantee uninterrupted, error-free platform operation.</li>
                            <li>We reserve the right to modify, suspend, or discontinue the platform at any time with or without notice.</li>
                            <li>We are not liable for data loss resulting from infrastructure failures, including Firebase service outages.</li>
                        </ul>
                    </Section>

                    <Section title="8. Termination">
                        <p>
                            We reserve the right to suspend or terminate accounts that violate these terms,
                            engage in abusive behavior, or attempt to misuse the platform. Account deletion
                            requests may be submitted to{" "}
                            <a href="mailto:privacy@sim-research.dev" className="auth-link">
                                privacy@sim-research.dev
                            </a>.
                        </p>
                    </Section>

                    <Section title="9. Modifications to Terms">
                        <p>
                            We may update these Terms and Conditions from time to time. Continued use of
                            the platform after changes constitute acceptance of the revised terms. The date
                            of the last update is noted at the top of this document.
                        </p>
                    </Section>

                    <Section title="10. Contact">
                        <p>
                            Questions about these terms may be directed to{" "}
                            <a href="mailto:hello@sim-research.dev" className="auth-link">
                                hello@sim-research.dev
                            </a>
                            , or via our{" "}
                            <a href="/contact" className="auth-link">Contact Page</a>.
                        </p>
                    </Section>
                </div>
            </section>
        </div>
    );
}
